version: 2.1
jobs:
  build_lint:
    docker:
    # Use the same Docker base as the project
    - image: cimg/node:12.22.4

    # working_directory: ~/app

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |

              sudo yarn install --production
              sudo yarn upgrade
              # Install hadolint
              sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              sudo chmod +x /bin/hadolint

      - run:
          name: run lint
          command: |
              sudo hadolint Dockerfile
              sudo yarn test
      
      - save_cache:
          paths:
            - ~/app
          key: build-cache
    
build-docker-image:
    docker:
    # Use the same Docker base as the project
    - image: cimg/node:12.22.4

    # working_directory: ~/app

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: set up image tag
          command: echo "export TAG=circleci-${CIRCLE_WORKFLOW_ID:0:7}" >> $BASH_ENV
      - run:
          name: create docker image
          command: |
            docker build -t capstone-app:$TAG .

workflows:
  default:
    jobs:
      - build-lint
      - build-docker-image:
          requires: [build-lint]