version: 2.1
jobs:
  build:
    docker:
    # Use the same Docker base as the project
    - image: circleci/node:13.8.0

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
              yarn install --production
              # Install hadolint
              wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint

      - run:
          name: run lint
          command: |
              hadolint Dockerfile
    
build-image:
    docker:
    # Use the same Docker base as the project
    - image: cimg/node:12.18.4

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: create and run container
          command: |


workflows:
  default:
    jobs:
      - build
      # - build-image