version: 2.1
jobs:
  build:
    docker:
    # Use the same Docker base as the project
    - image: cimg/node:12.22.4

    # working_directory: ~/app

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
              sudo yarn install --production
              # Install hadolint
              sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              sudo chmod +x /bin/hadolint
              sudo yarn test

      - run:
          name: run lint
          command: |
              sudo hadolint Dockerfile
              sudo yarn test
      
      - save_cache:
          paths:
            - ~/app
          key: build-cache
    
build-image:
    docker:
    # Use the same Docker base as the project
    - image: cimg/node:12.18.4

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: create and run container
          command: |


workflows:
  default:
    jobs:
      - build
      # - build-image